import PDFDocument from "pdfkit";
import { round1, fmtPct, fmtHours, fmtDate, isOverrun } from "@/lib/format";
import type { ReportData } from "@/lib/report/types";
import type { ProjectMetrics } from "@/lib/types";

const BLUE = "#2563eb";
const RED = "#dc2626";
const GRAY = "#6b7280";

// Spec 08 §3.1 — PDF: cover/header, portfolio summary + charts, per-project detail.
export async function buildPdf(data: ReportData): Promise<Buffer> {
  const doc = new PDFDocument({ size: "A4", margin: 40 });
  const done = collect(doc); // attaches listeners only; we call doc.end() at the very end
  const left = doc.page.margins.left;
  const width = doc.page.width - doc.page.margins.left - doc.page.margins.right;

  // ---- Header ----
  doc.fillColor("#111827").font("Helvetica-Bold").fontSize(20).text("PM Dashboard — Report");
  doc.moveDown(0.3);
  doc.font("Helvetica").fontSize(10).fillColor(GRAY);
  doc.text(data.scopeLabel);
  doc.text(`Generated by ${data.generatedBy}`);
  doc.text(`Generated at ${data.generatedAt.toLocaleString()}`);
  doc.moveDown(0.8);
  hr(doc, left, width);
  doc.moveDown(0.6);

  // ---- Portfolio summary ----
  const statusCounts = tally(data.projects.map((p) => p.status_label ?? "—"));
  const priorityCounts = tally(data.projects.map((p) => p.priority));
  const completions = data.projects
    .map((p) => p.pct_completion)
    .filter((v): v is number => v != null);
  const avg = completions.length ? completions.reduce((a, b) => a + b, 0) / completions.length : null;
  const overCount = data.projects.filter((p) => isOverrun(p.pct_completion)).length;

  section(doc, "Portfolio Summary");
  doc.font("Helvetica").fontSize(10).fillColor("#111827");
  doc.text(`Projects in scope: ${data.projects.length}`);
  doc.text(`Average % Completion: ${avg == null ? "—" : `${round1(avg)}%`}`);
  doc.fillColor(overCount > 0 ? RED : "#111827").text(`Projects OVER 100%: ${overCount}`);
  doc.fillColor("#111827");
  doc.moveDown(0.6);

  // Charts: status distribution + man-hours by person.
  barChart(doc, "Projects by Status", statusCounts, left, width / 2 - 10);
  const hoursByPerson = tallySum(data.team.map((t) => [t.person, t.allocated_hours] as [string, number]))
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10);
  const chartY = doc.y;
  doc.y = chartY; // second chart to the right of the first (approx side-by-side)
  barChart(doc, "Man-hours by Person (recent)", hoursByPerson, left + width / 2 + 10, width / 2 - 10, chartY - chartHeight(statusCounts.length));

  doc.moveDown(0.6);
  hr(doc, left, width);
  doc.moveDown(0.6);

  // ---- Per-project detail ----
  section(doc, "Per-Project Detail");
  for (const p of data.projects) {
    projectBlock(doc, p, data, left, width);
  }

  doc.end(); // finalize AFTER all content is drawn
  return done;
}

// ---------------------------------------------------------------------------
function projectBlock(doc: PDFKit.PDFDocument, p: ProjectMetrics, data: ReportData, left: number, width: number) {
  ensureSpace(doc, 150);
  doc.moveDown(0.4);
  doc.font("Helvetica-Bold").fontSize(12).fillColor("#111827").text(p.project_name, { continued: true });
  if (isOverrun(p.pct_completion)) {
    doc.fillColor(RED).font("Helvetica-Bold").fontSize(9).text("   OVER");
  } else {
    doc.text("");
  }
  doc.fillColor("#111827").font("Helvetica").fontSize(9);

  const rows: [string, string][] = [
    ["Stakeholder", p.stakeholder],
    ["Type", p.project_type_label ?? "—"],
    ["Priority", p.priority],
    ["Status", p.status_label ?? "—"],
    ["Manager/Lead", p.manager_lead_name ?? "—"],
    ["Start → End", `${fmtDate(p.start_date)} → ${fmtDate(p.planned_end_date)}`],
    ["Estimated Hrs", fmtHours(p.estimated_effort_hrs)],
    ["Logged Hrs", fmtHours(p.logged_hours)],
    ["% Completion", fmtPct(p.pct_completion)],
    ["Pending Hrs", fmtHours(p.pending_hours)],
    ["Planned Hrs", fmtHours(p.planned_hours)],
    ["Allocation %", fmtPct(p.allocation_pct)],
    ["Working days left", String(p.working_days_remaining)],
  ];
  const colW = width / 2;
  let y = doc.y + 4;
  rows.forEach(([k, v], i) => {
    const x = left + (i % 2) * colW;
    if (i % 2 === 0 && i > 0) y += 14;
    doc.fillColor(GRAY).text(`${k}: `, x, y, { continued: true });
    doc.fillColor("#111827").text(v);
  });
  doc.y = y + 18;

  if (p.description) {
    doc.fillColor(GRAY).font("Helvetica-Oblique").fontSize(8).text(`Description: ${p.description}`, { width });
    doc.font("Helvetica").fillColor("#111827");
  }

  // Team roster — each allocation with its range and man-hours.
  const roster = data.team
    .filter((t) => t.project_name === p.project_name)
    .sort((a, b) => a.person.localeCompare(b.person) || a.start_date.localeCompare(b.start_date));
  if (roster.length) {
    doc.fillColor(GRAY).font("Helvetica-Oblique").fontSize(8).text("Team roster:");
    doc.font("Helvetica").fillColor("#111827").fontSize(8);
    roster.forEach((r) =>
      doc.text(`  • ${r.person} — ${r.allocated_hours} hrs  (${r.start_date} → ${r.end_date})`)
    );
  }
  doc.moveDown(0.3);
  hr(doc, left, width, "#e5e7eb");
}

// ---- small drawing helpers ----
function section(doc: PDFKit.PDFDocument, title: string) {
  ensureSpace(doc, 40);
  doc.font("Helvetica-Bold").fontSize(13).fillColor("#111827").text(title);
  doc.moveDown(0.3);
}

function hr(doc: PDFKit.PDFDocument, x: number, w: number, color = "#d1d5db") {
  doc.strokeColor(color).lineWidth(0.5).moveTo(x, doc.y).lineTo(x + w, doc.y).stroke();
}

function chartHeight(n: number) {
  return 24 + n * 16 + 10;
}

function barChart(
  doc: PDFKit.PDFDocument,
  title: string,
  entries: [string, number][],
  x: number,
  w: number,
  yOverride?: number
) {
  let y = yOverride ?? doc.y;
  doc.font("Helvetica-Bold").fontSize(9).fillColor("#111827").text(title, x, y);
  y += 16;
  const max = Math.max(1, ...entries.map((e) => e[1]));
  const labelW = 90;
  const barMax = w - labelW - 30;
  for (const [label, value] of entries) {
    doc.font("Helvetica").fontSize(8).fillColor(GRAY).text(truncate(label, 16), x, y, { width: labelW });
    const barW = Math.max(1, (value / max) * barMax);
    doc.rect(x + labelW, y, barW, 8).fill(BLUE);
    doc.fillColor("#111827").fontSize(8).text(String(round1(value)), x + labelW + barW + 4, y - 1);
    y += 16;
  }
  doc.y = Math.max(doc.y, y + 6);
}

function ensureSpace(doc: PDFKit.PDFDocument, needed: number) {
  const bottom = doc.page.height - doc.page.margins.bottom;
  if (doc.y + needed > bottom) doc.addPage();
}

function tally(values: string[]): [string, number][] {
  const m = new Map<string, number>();
  for (const v of values) m.set(v, (m.get(v) ?? 0) + 1);
  return Array.from(m.entries()).sort((a, b) => b[1] - a[1]);
}

function tallySum(pairs: [string, number][]): [string, number][] {
  const m = new Map<string, number>();
  for (const [k, v] of pairs) m.set(k, (m.get(k) ?? 0) + v);
  return Array.from(m.entries());
}

function truncate(s: string, n: number) {
  return s.length > n ? `${s.slice(0, n - 1)}…` : s;
}

// Attaches stream listeners only. The caller must call doc.end() after drawing
// all content — ending here would finalize the (empty) document immediately.
function collect(doc: PDFKit.PDFDocument): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });
}
